# generic node.js base image
FROM node:7-onbuild

# used so docker can see if its up or not
HEALTHCHECK --interval=5s \
            --timeout=5s \
            CMD curl -f http://127.0.0.1:8000 || exit 1

# local container port - not the host port
EXPOSE 8000